"""empty message

Revision ID: e5bf727be496
Revises: 0984cb98f212
Create Date: 2021-12-01 07:56:53.879031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bf727be496'
down_revision = '0984cb98f212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
