"""empty message

Revision ID: d7f286e280b1
Revises: bb0cc6b029ac
Create Date: 2021-12-01 08:00:43.949261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f286e280b1'
down_revision = 'bb0cc6b029ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('username', sa.String(length=40), nullable=False))
    op.add_column('scores', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('scores', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'scores', ['username'])
    op.create_unique_constraint(None, 'scores', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scores', type_='unique')
    op.drop_constraint(None, 'scores', type_='unique')
    op.drop_column('scores', 'hashed_password')
    op.drop_column('scores', 'email')
    op.drop_column('scores', 'username')
    # ### end Alembic commands ###
